package hibernateexample;
// Generated May 25, 2017 4:37:42 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private Integer id;
     private String firstName;
     private String lastName;
     private Integer salary;
     private Set phones;

    public Employee() {
    }

    public Employee(String firstName, String lastName, Integer salary, Set<Phone> phones) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.salary = salary;
       this.phones = phones;
    }
    Employee(String fname, String lname, int salary) {
        this.firstName = fname;
        this.lastName = lname;
        this.salary = salary;
    }

   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Integer getSalary() {
        return this.salary;
    }
    
    public void setSalary(Integer salary) {
        this.salary = salary;
    }
    public Set getPhones() {
        return this.phones;
    }
    
    public void setPhones(Set phones) {
        this.phones = phones;
    }

}


